name: build-cron

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        configurations: [Debug, Release]
        frameworks: [net8.0, netstandard2.1]
        include:
          - frameworks: net8.0
            projects: MascotCapsule.Schemas.sln
          - frameworks: netstandard2.1
            projects: MascotCapsule.Schemas.sln
    steps:
      - uses: kagekirin/gha-py-toolbox/macros/util/setup-system@main
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          systems: |
            python
            dotnet
